version: "3.3" 
services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=FlaskApp
    links:
      - postgres
    depends_on:
      - postgres
    expose:
      - 8080
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
